### ISSUE TITLE
Laravel 5.4 issues

### ISSUE THREAD

**Issue by kel** [irazasyed/laravel-identicon#4]
After upgrading to Laravel 5.4 I get the following error.

`
[2017-01-29 14:58:58] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in C:\app\vendor\irazasyed\laravel-identicon\src\Irazasyed\LaravelIdenticon\ServiceProvider.php:29
Stack trace:
#0 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(568): Irazasyed\LaravelIdenticon\ServiceProvider->register()
#1 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(677): Illuminate\Foundation\Application->register(Object(Irazasyed\LaravelIdenticon\ServiceProvider))
#2 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(657): Illuminate\Foundation\Application->registerDeferredProvider('Irazasyed\\Larav...', 'identicon')
#3 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(633): Illuminate\Foundation\Application->loadDeferredProvider('identicon')
#4 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(276): Illuminate\Foundation\Application->loadDeferredProviders()
#5 C:\app\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#6 C:\app\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main} 
`

**Comment by davidpiesse** [comment]
share() has been removed.
The new way is to use singleton. it is documented in the upgrade notes for 5.4
